# Generated by Django 5.0.1 on 2024-01-21 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MusicTrack",
            fields=[
                ("index", models.PositiveIntegerField(unique=True)),
                (
                    "id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("title", models.CharField(max_length=255)),
                ("danceability", models.FloatField()),
                ("energy", models.FloatField()),
                ("key", models.IntegerField()),
                ("loudness", models.FloatField()),
                ("mode", models.IntegerField()),
                ("acousticness", models.FloatField()),
                ("instrumentalness", models.FloatField()),
                ("liveness", models.FloatField()),
                ("valence", models.FloatField()),
                ("tempo", models.FloatField()),
                ("duration_ms", models.IntegerField()),
                ("time_signature", models.IntegerField()),
                ("num_bars", models.IntegerField()),
                ("num_sections", models.IntegerField()),
                ("num_segments", models.IntegerField()),
                ("class_field", models.CharField(max_length=255)),
            ],
        ),
    ]
