# Generated by Django 5.0.1 on 2024-01-21 08:36

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="musictrack",
            index=models.Index(fields=["title"], name="MusicTrack_title_29ba5d_idx"),
        ),
        migrations.AlterModelTable(
            name="musictrack",
            table="MusicTrack",
        ),
    ]
