# Generated by Django 5.0.1 on 2024-01-21 11:51

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_musictrack_musictrack_title_29ba5d_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="musictrack",
            name="rating",
            field=models.IntegerField(default=0),
        ),
    ]
